# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'github-actions' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: all
    commit-message:
      include: scope
      prefix: '[github-actions] '
    labels:
      - github-actions
      - dependencies
    assignees:
      - 'danielstals'
    reviewers:
      - 'danielstals'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-type: all
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '/'
    commit-message:
      include: scope
      prefix: '[dep|pnpm] '
    labels:
      - pnpm
      - dependencies
    versioning-strategy: increase-if-necessary
    assignees:
      - 'danielstals'
    reviewers:
      - 'danielstals'
    ignore:
      - dependency-name: '@upstash/rag-chat'
    groups:
      breaking-security-updates:
        applies-to: security-updates
        update-types:
          - major
      security-updates:
        applies-to: security-updates
        update-types:
          - minor
          - patch
      breaking-version-updates:
        applies-to: version-updates
        update-types:
          - major
      version-updates:
        applies-to: version-updates
        update-types:
          - minor
          - patch
