name: e2e-reusable

on: workflow_call

jobs:
  i:
    timeout-minutes: 60
    runs-on: macos-latest
    env:
      TZ: Europe/Amsterdam

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: ./.github/actions/pnpm-install

      - name: Install playwright
        uses: ./.github/actions/playwright-install

      - name: Run Playwright
        run: pnpm test:e2e:ci

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10
