name: Fix Dependabot

on:
  pull_request:
    branches:
      - dependabot/**

permissions: read-all

jobs:
  sync-lockfile:
    runs-on: macos-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - run: pnpm i --lockfile-only

      - name: Commit lockfile changes
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git add pnpm-lock.yaml
          git commit -m "build(deps): update pnpm-lock.yaml"
          git push
