name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: ./.github/actions/pnpm-install

      - name: Lint
        run: pnpm lint

  unit_tests:
    name: Run Jest Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: ./.github/actions/pnpm-install

      - name: Run Jest Tests
        run: pnpm test:ci

  e2e_tests:
    needs: [unit_tests]
    name: Run Playwright E2E Tests
    timeout-minutes: 60
    runs-on: macos-latest
    env:
      TZ: Europe/Amsterdam

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: ./.github/actions/pnpm-install

      - name: Install playwright
        uses: ./.github/actions/playwright-install

      - name: Run Playwright
        run: pnpm test:e2e:ci

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10

  deploy_preview:
    needs: [unit_tests, e2e_tests]
    name: Deploy to Preview
    runs-on: macos-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: ./.github/actions/pnpm-install

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
