name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  TZ: Europe/Amsterdam
  NEXT_PUBLIC_UNDER_CONSTRUCTION: false
  LANGCHAIN_TRACING_V2: true
  LANGCHAIN_CALLBACKS_BACKGROUND: true
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  LANGCHAIN_ENDPOINT: ${{ secrets.LANGCHAIN_ENDPOINT }}
  LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
  LANGCHAIN_PROJECT: ${{ secrets.LANGCHAIN_PROJECT }}
  UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
  UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
  UPSTASH_VECTOR_REST_URL: ${{ secrets.UPSTASH_VECTOR_REST_URL }}
  UPSTASH_VECTOR_REST_TOKEN: ${{ secrets.UPSTASH_VECTOR_REST_TOKEN }}

on:
  push:
    branches-ignore:
      - main

jobs:
  # https://github.com/dependabot/dependabot-core/issues/1736
  dependabot_fix:
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/heads/dependabot/')
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: '^8'
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: pnpm i --lockfile-only
      - run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git add pnpm-lock.yaml
          git commit -m "chore: dependabot[bot] update pnpm-lock.yaml"
          git push

  lint:
    needs: [dependabot_fix]
    name: Run Linter
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: ./.github/actions/pnpm-install

      - name: Lint
        run: pnpm lint

  unit_tests:
    needs: [dependabot_fix]
    name: Run Jest Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: ./.github/actions/pnpm-install

      - name: Run Jest Tests
        run: pnpm test:ci

  e2e_tests:
    needs: [dependabot_fix]
    name: Run Playwright E2E Tests
    timeout-minutes: 60
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: ./.github/actions/pnpm-install

      - name: Install playwright
        uses: ./.github/actions/playwright-install

      - name: Build Export
        uses: ./.github/actions/nextjs-build-export
        with:
          e2e: 'true'

      - name: Run Playwright
        run: pnpm test:e2e:ci

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10

  deploy_preview:
    needs: [dependabot_fix, lint, unit_tests, e2e_tests]
    name: Deploy to Preview
    runs-on: macos-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: ./.github/actions/pnpm-install

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
